# Generated by Django 4.1 on 2022-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery_1',
            field=models.ImageField(blank=True, default='default.png', upload_to='project/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_2',
            field=models.ImageField(blank=True, default='default.png', upload_to='project/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_3',
            field=models.ImageField(blank=True, default='default.png', upload_to='project/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_4',
            field=models.ImageField(blank=True, default='default.png', upload_to='project/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.png', upload_to='project/%y/%m/%d/'),
        ),
    ]
