# Generated by Django 4.1 on 2022-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
