# Generated by Django 4.1 on 2022-09-10 08:38

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(validators=[contact.models.bad_words_validators]),
        ),
    ]
