# Generated by Django 4.1 on 2022-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
