# Generated by Django 4.1 on 2022-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_social_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
