# Generated by Django 4.1 on 2022-09-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
