# Generated by Django 4.1 on 2022-09-03 07:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills_iamge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='services/%y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='location',
            field=models.CharField(default=1, max_length=225),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(default=1, max_length=225),
        ),
    ]
