# Generated by Django 4.1 on 2022-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services_siteinfo_location_siteinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/%y/%m/%d/'),
        ),
    ]
