# Generated by Django 4.1 on 2022-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default=1, max_length=225),
        ),
        migrations.AddField(
            model_name='orders',
            name='reciever',
            field=models.CharField(default=1, max_length=225),
        ),
    ]
