# Generated by Django 4.1 on 2022-10-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_address_orders_reciever'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Submmited Orders'},
        ),
    ]
